-- 기존 Notice / Qa 테이블과 시퀀스 삭제
drop table Notice purge;
drop sequence Notice_seq;
drop table QA purge;
drop sequence QA_seq;

-- QA(1:1문의) 테이블 생성
create table QA
(  num NUMBER(6) PRIMARY KEY,
    category varchar2(20),
    writeDay DATE DEFAULT SYSDATE,
    title varchar2(500),
    contents varchar2(3900),
	answer varchar2(3900),
    userid  varchar2(20)
);   
   
-- QA에 userid FK 추가
alter table QA
add CONSTRAINT QA_userid_fk FOREIGN KEY(userid)
REFERENCES member(userid) ON DELETE CASCADE;

-- QA 번호 시퀀스 생성
create sequence QA_seq;

-- Notice(공지사항) 테이블 생성
create table Notice
(  num NUMBER(6) PRIMARY KEY,
    writeDay DATE DEFAULT SYSDATE,
    title varchar2(500),
    contents varchar2(3900),
    writer varchar2(500),
    viewcount NUMBER(6)
);   

-- Notice 번호 시퀀스 생성
create sequence notice_seq;

-- Insert
-- Notice 더미 데이터
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항1', '공지사항1입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항2', '공지사항2입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항3', '공지사항3입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항4', '공지사항4입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항5', '공지사항5입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항6', '공지사항7입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항8', '공지사항8입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항9', '공지사항9입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항10', '공지사항10입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항11', '공지사항11입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항12', '공지사항12입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항13', '공지사항13입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항14', '공지사항14입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항15', '공지사항15입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항16', '공지사항16입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항17', '공지사항17입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항18', '공지사항18입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항19', '공지사항19입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항20', '공지사항20입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항21', '공지사항21입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항22', '공지사항22입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항23', '공지사항23입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항24', '공지사항24입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항25', '공지사항25입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항26', '공지사항26입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항27', '공지사항27입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항28', '공지사항28입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항29', '공지사항29입니다', '관리자', 0 );
INSERT INTO NOTICE ( NUM, WRITEDAY, TITLE, CONTENTS, WRITER, VIEWCOUNT )
VALUES ( NOTICE_SEQ.NEXTVAL, SYSDATE, '공지사항30', '공지사항30입니다', '관리자', 0 );
COMMIT;